steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/cloudrunbuilder:latest'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/cloudrunbuilder:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/cloudrunbuilder:latest'

- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - "beta"
  - "run"
  - "deploy"
  - "cloudrunbuilder"
  - "--image=gcr.io/$PROJECT_ID/cloudrunbuilder"
  - "--platform=managed"
  - "--region=asia-northeast1"
  - "--allow-unauthenticated"
  - "--memory=64Mi"
  - "--service-account=ryoya3091@gmail.com"  

